%%{init: {'theme':'default'}}%%
gantt
    todayMarker off
    title Project Timeline - Part 1
    dateFormat YYYY-MM-DD
    
    section Søren
    Filter for HIs during scanning           :a1, 2025-09-23, 7d
    Connect to HI                            :a2, 2025-09-23, 7d
    Pair with HI                             :a3, 2025-09-23, 7d
    Implement VCP Controller                 :a4, 2025-09-30, 7d
    Implement Battery Service                :a5, 2025-09-30, 7d
    Implement Coordinated Sets               :a6, 2025-10-07, 7d
    Implement Hearing Access Service         :a7, 2025-10-07, 14d
    Write Report                             :a8, 2025-10-21, 28d
    Implement sleep mode                     :a9, 2025-11-18, 7d
    
    section Jonas
    Scan for devices                         :b1, 2025-09-23, 7d
    Implement Volume Up Button               :b2, 2025-09-30, 14d
    Implement Volume Down Button             :b3, 2025-09-30, 14d
    Implement Pairing Button                 :b4, 2025-10-07, 14d
    Write Report                             :b5, 2025-10-21, 28d
    Implement OLED                           :b6, 2025-11-18, 7d