%%{init: {'theme':'default'}}%%
gantt
    todayMarker off
    title Project Timeline - Part 2
    dateFormat YYYY-MM-DD
    
    section Søren
    Implement sleep mode                     :c1, 2025-11-25, 21d
    Implement wake from sleep                :c2, 2025-12-16, 14d
    Buffer/Writing                           :c3, 2025-12-30, 16d
    Turn in project                          :milestone, c4, 2026-01-15, 1d
    
    section Jonas
    Implement OLED                           :d1, 2025-11-25, 7d
    Write Report                             :d2, 2025-12-02, 7d
    Implement sleep mode                     :d3, 2025-12-09, 7d
    Implement wake from sleep                :d4, 2025-12-16, 14d
    Buffer/Writing                           :d5, 2025-12-30, 16d
    Turn in project                          :milestone, d6, 2026-01-15, 1d